# Missing Values Overview

In [139]:
import pandas as pd
import numpy as np

WorldData = pd.read_csv("WorldMarketData.csv", na_values = '..')
df_original = pd.DataFrame(WorldData)
pd.options.display.float_format = '{:,.2f}'.format
df_original.columns = ['country', 'country_code', 'series', 'series_code', '1994', '1995', '1996', '1997', '1998', 
             '1999', '2000', '2001', '2002', '2003', '2004', '2005', '2006', '2007', '2008', '2009', '2010', '2011', 
             '2012', '2013', '2014', '2015', '2016', '2017', '2018']

df = df_original.drop(columns=['country_code', 'series_code'])
df = df.drop(df.index[3800:])
df1 = pd.melt(df,
                       ["country", 'series'],
                       var_name="year",
                       value_name="value")
#df1 = df1.sort_values(by=["year"], ascending = True)
df1 = df1.set_index('country').drop(index = ['World', 'Low income', 'Middle income', 'High income'])
df1 = df1.reset_index()
df1.head()

,country,series,year,value
0,United States,Agricultural raw materials exports (% of merch...,1994,3.49
1,United States,Agricultural raw materials imports (% of merch...,1994,2.04
2,United States,Average time to clear exports through customs ...,1994,nan
3,United States,Bribery incidence (% of firms experiencing at ...,1994,nan
4,United States,Changes in inventories (current US$),1994,"63,785,000,000.00"

In [140]:
#Copy the Untidy WMDA Data (df)
df_overview = df.copy()

In [141]:
#Add a Total Missing Values Column
df_overview['Missing_Values'] = df_overview.apply(lambda x: x.isna().sum(), axis=1)

In [142]:
#Only display the country, series, and Missing_Values column
#Sort the missing data overview by the most missing values across the years
#Either of the below methods achieves the same result

df_overview = df_overview[['country', 'series', 'Missing_Values']]
df_overview = df_overview.set_index('country')
#df_overview = df_overview[df_overview.Missing_Values != 0]
df_overview = df_overview.sort_values(by = "Missing_Values", ascending = False)
df_overview.head(10)

                                                       series  Missing_Values
country
Luxembourg  Average time to clear exports through customs ...              25
Italy       Presence of peace keepers (number of troops, p...              25
Zimbabwe      Research and development expenditure (% of GDP)              25
Zimbabwe              Researchers in R&D (per million people)              25
Italy       Public private partnerships investment in ener...              25
Italy       Public private partnerships investment in ICT ...              25
Zimbabwe              Technicians in R&D (per million people)              25
Belgium     Public private partnerships investment in ICT ...              25
Belgium     Public private partnerships investment in ener...              25
Belgium     Presence of peace keepers (number of troops, p...              25

# Find the Years with the least NaN values/ least missing entries

In [143]:
#Find the years with the least NaN values/least missing entries
df.isna().sum().sort_values(ascending = True).to_frame()

            0
country     0
series      0
2014      546
2016      560
2010      966
2015      974
2012      981
2007      997
2017     1159
2013     1372
2011     1407
2006     1429
2009     1434
2008     1435
2005     1537
2018     1665
2004     1688
2003     1739
2002     1855
2001     1874
2000     1902
1999     1933
1998     1959
1997     1973
1996     1976
1995     2067
1994     2146

# Finding Series with the least NaN Values

In [144]:
#Finding Series with the least NaN Values
df = df.set_index('series')
series_counts = df.isna().sum(axis = 1).sort_values(ascending = True).to_frame()
series_totals = series_counts.groupby('series').sum()
series_totals_sorted = series_totals.sort_values(0, ascending = True)
df = df.reset_index()
series_totals_sorted.head(20)

                                                      0
series
GDP per capita (current US$)                          0
GDP (current US$)                                     0
GNI (current US$)                                     6
GDP per capita growth (annual %)                      7
GDP growth (annual %)                                 7
GNI, Atlas method (current US$)                      14
GNI per capita, Atlas method (current US$)           14
Trade (% of GDP)                                     18
Imports of goods and services (% of GDP)             18
Exports of goods and services (% of GDP)             18
Exports of goods and services (current US$)          37
Imports of goods and services (current US$)          37
Gross capital formation (current US$)                43
Industry (including construction), value added ...   59
Manufacturing, value added (current US$)             83
Manufacturing, value added (% of GDP)                85
Imports of goods and services (annual % growth)      94
GNI per capita growth (annual %)                    103
GNI growth (annual %)                               103
Exports of goods and services (annual % growth)     104

# Finding Country with the least NaN Values

In [145]:
#Finding Country with the least NaN Values
df = df.set_index('country')
country_counts = df.isna().sum(axis = 1).sort_values(ascending = True).to_frame()

#Total Missing Values Per Country
country_totals = country_counts.groupby('country').sum()
country_totals_sorted = country_totals.sort_values(0, ascending = True)
df = df.reset_index()
country_totals_sorted.head(20)

                  0
country
Argentina       612
Colombia        654
Korea, Rep.     663
Germany         664
Singapore       668
United Kingdom  668
Costa Rica      669
Peru            669
Spain           670
Mexico          672
Netherlands     672
Philippines     675
Guatemala       677
France          678
Malaysia        682
Chile           684
Italy           685
Panama          686
El Salvador     689
Brazil          693

# Missing Values (by Years) Overview

In [146]:
df_mv = df_overview.reset_index()
df_mv = df_mv.pivot_table(index = ['country'], columns = 'series', values='Missing_Values')
df_mv = df_mv.reset_index()
df_mv = df_mv.set_index('country')
df_mv.head()

series,Agricultural raw materials exports (% of merchandise exports),Agricultural raw materials imports (% of merchandise imports),Average time to clear exports through customs (days),Bribery incidence (% of firms experiencing at least one bribe payment request),Changes in inventories (current US$),Commercial service exports (current US$),Commercial service imports (current US$),"Computer, communications and other services (% of commercial service exports)","Computer, communications and other services (% of commercial service imports)",Cost of business start-up procedures (% of GNI per capita),...,"Tariff rate, applied, simple mean, all products (%)","Tariff rate, most favored nation, weighted mean, all products (%)",Technicians in R&D (per million people),Time required to build a warehouse (days),Time required to start a business (days),"Time to export, border compliance (hours)","Time to export, documentary compliance (hours)","Time to import, border compliance (hours)","Time to import, documentary compliance (hours)",Trade (% of GDP)
country,,,,,,,,,,,,,,,,,,,,,
Argentina,0,0,22,22,0,0,0,0,0,9,...,2,2,5,11,9,20,20,20,20,0
Australia,0,0,25,25,0,0,0,0,0,9,...,3,3,18,11,9,20,20,20,20,0
Bahrain,5,5,25,25,1,1,1,1,1,13,...,6,6,24,13,13,20,20,20,20,0
Belgium,0,0,25,25,0,8,8,8,8,9,...,1,1,9,11,9,20,20,20,20,0
Brazil,1,1,24,24,0,0,0,0,0,19,...,1,1,18,19,19,20,20,20,20,0

Had previously tried:
>`df_mv.reindex(df_mv.mean().sort_values(ascending = False).index, axis=1 )`

But it did not work because it got rid of the country labels

In [147]:
#Shows the number of years missing the value for that given series, for the given country
#For series wherein almost all the countries are missing over 20 years of data... these series should not be included.

rows_index=df_mv.mean(axis=1).sort_values(ascending=False).index
col_index=df_mv.mean().sort_values(ascending=False).index
dfmv=df_mv.loc[rows_index,col_index]
dfmv.head()

series,"Presence of peace keepers (number of troops, police, and military observers in mandate)",Public private partnerships investment in ICT (current US$),Firms that spend on R&D (% of firms),Ease of doing business index (1=most business-friendly regulations),Bribery incidence (% of firms experiencing at least one bribe payment request),Average time to clear exports through customs (days),"Lead time to import, median case (days)","Lead time to export, median case (days)",Logistics performance index: Quality of trade and transport-related infrastructure (1=low to 5=high),Logistics performance index: Ability to track and trace consignments (1=low to 5=high),...,Exports of goods and services (% of GDP),Imports of goods and services (% of GDP),Trade (% of GDP),"GNI per capita, Atlas method (current US$)","GNI, Atlas method (current US$)",GDP growth (annual %),GDP per capita growth (annual %),GNI (current US$),GDP (current US$),GDP per capita (current US$)
country,,,,,,,,,,,,,,,,,,,,,
Low income,25,25,24,25,24,24,20,20,20,20,...,4,4,4,0,0,0,0,0,0,0
United Arab Emirates,25,25,25,24,25,25,20,20,20,20,...,7,7,7,6,6,0,0,6,0,0
Qatar,25,25,25,24,25,25,20,20,20,20,...,1,1,1,8,8,7,7,0,0,0
"Congo, Dem. Rep.",16,24,24,24,22,22,23,22,21,21,...,0,0,0,0,0,0,0,0,0,0
Middle income,25,25,24,25,24,24,20,20,20,20,...,0,0,0,0,0,0,0,0,0,0

In [148]:
#Drop first 10 columns because they are missing roughly all the years of data for that series
dfmv.drop(dfmv.iloc[:, 0:10], inplace = True, axis = 1)
dfmv.head()

series,Logistics performance index: Ease of arranging competitively priced shipments (1=low to 5=high),Logistics performance index: Efficiency of customs clearance process (1=low to 5=high),Logistics performance index: Frequency with which shipments reach consignee within scheduled or expected time (1=low to 5=high),Logistics performance index: Overall (1=low to 5=high),Logistics performance index: Competence and quality of logistics services (1=low to 5=high),"Time to import, documentary compliance (hours)","Cost to export, border compliance (US$)","Cost to export, documentary compliance (US$)","Cost to import, documentary compliance (US$)","Cost to import, border compliance (US$)",...,Exports of goods and services (% of GDP),Imports of goods and services (% of GDP),Trade (% of GDP),"GNI per capita, Atlas method (current US$)","GNI, Atlas method (current US$)",GDP growth (annual %),GDP per capita growth (annual %),GNI (current US$),GDP (current US$),GDP per capita (current US$)
country,,,,,,,,,,,,,,,,,,,,,
Low income,20,20,20,20,20,20,20,20,20,20,...,4,4,4,0,0,0,0,0,0,0
United Arab Emirates,20,20,20,20,20,20,20,20,20,20,...,7,7,7,6,6,0,0,6,0,0
Qatar,20,20,20,20,20,20,20,20,20,20,...,1,1,1,8,8,7,7,0,0,0
"Congo, Dem. Rep.",21,21,21,21,21,20,20,20,20,20,...,0,0,0,0,0,0,0,0,0,0
Middle income,20,20,20,20,20,20,20,20,20,20,...,0,0,0,0,0,0,0,0,0,0

# Stacked Data for Visibility and Formatting Flexibility

In [149]:
#Get the series as the columns using Stack (could have used pivot if desired)

df_stack = df1.set_index(['series', 'country'])
df_stack_all = df_stack

dfsa = df_stack_all.reset_index()
dfsa = dfsa.pivot_table(index = ['country', 'year'], columns = 'series', values='value')
dfsa = dfsa.reset_index()
dfsa.head()

series,country,year,Agricultural raw materials exports (% of merchandise exports),Agricultural raw materials imports (% of merchandise imports),Average time to clear exports through customs (days),Bribery incidence (% of firms experiencing at least one bribe payment request),Changes in inventories (current US$),Commercial service exports (current US$),Commercial service imports (current US$),"Computer, communications and other services (% of commercial service exports)",...,"Tariff rate, applied, simple mean, all products (%)","Tariff rate, most favored nation, weighted mean, all products (%)",Technicians in R&D (per million people),Time required to build a warehouse (days),Time required to start a business (days),"Time to export, border compliance (hours)","Time to export, documentary compliance (hours)","Time to import, border compliance (hours)","Time to import, documentary compliance (hours)",Trade (% of GDP)
0,Argentina,1994,3.36,1.62,nan,nan,"68,602,700.00","3,180,600,000.00","6,856,100,000.00",10.34,...,nan,nan,nan,nan,nan,nan,nan,nan,nan,18.13
1,Argentina,1995,4.32,2.03,nan,nan,"1,451,852,800.00","3,664,500,000.00","6,961,200,000.00",11.16,...,12.70,11.41,nan,nan,nan,nan,nan,nan,nan,19.77
2,Argentina,1996,3.81,1.91,nan,nan,"4,195,708,700.00","4,239,554,642.49","7,623,604,066.22",12.05,...,14.45,13.40,nan,nan,nan,nan,nan,nan,nan,21.51
3,Argentina,1997,2.84,1.55,nan,nan,"4,263,816,100.00","4,430,771,471.36","8,675,186,708.79",10.91,...,14.44,13.93,159.12,nan,nan,nan,nan,nan,nan,23.34
4,Argentina,1998,2.11,1.50,nan,nan,"3,096,528,400.00","4,694,769,562.61","9,047,117,536.80",10.48,...,16.73,15.67,169.89,nan,nan,nan,nan,nan,nan,23.35

There are many series with too many NaN values, so we will drop these using the code below

In [150]:
#Drop columns with certain number of NaN
dfsa = dfsa.dropna(thresh=len(dfsa) - 1000, axis=1)
dfsa.head()

series,country,year,Agricultural raw materials exports (% of merchandise exports),Agricultural raw materials imports (% of merchandise imports),Changes in inventories (current US$),Commercial service exports (current US$),Commercial service imports (current US$),"Computer, communications and other services (% of commercial service exports)","Computer, communications and other services (% of commercial service imports)",Cost of business start-up procedures (% of GNI per capita),...,"Tariff rate, applied, simple mean, all products (%)","Tariff rate, most favored nation, weighted mean, all products (%)",Technicians in R&D (per million people),Time required to build a warehouse (days),Time required to start a business (days),"Time to export, border compliance (hours)","Time to export, documentary compliance (hours)","Time to import, border compliance (hours)","Time to import, documentary compliance (hours)",Trade (% of GDP)
0,Argentina,1994,3.36,1.62,"68,602,700.00","3,180,600,000.00","6,856,100,000.00",10.34,15.34,nan,...,nan,nan,nan,nan,nan,nan,nan,nan,nan,18.13
1,Argentina,1995,4.32,2.03,"1,451,852,800.00","3,664,500,000.00","6,961,200,000.00",11.16,15.46,nan,...,12.70,11.41,nan,nan,nan,nan,nan,nan,nan,19.77
2,Argentina,1996,3.81,1.91,"4,195,708,700.00","4,239,554,642.49","7,623,604,066.22",12.05,15.61,nan,...,14.45,13.40,nan,nan,nan,nan,nan,nan,nan,21.51
3,Argentina,1997,2.84,1.55,"4,263,816,100.00","4,430,771,471.36","8,675,186,708.79",10.91,15.94,nan,...,14.44,13.93,159.12,nan,nan,nan,nan,nan,nan,23.34
4,Argentina,1998,2.11,1.50,"3,096,528,400.00","4,694,769,562.61","9,047,117,536.80",10.48,16.90,nan,...,16.73,15.67,169.89,nan,nan,nan,nan,nan,nan,23.35

In [151]:
# Set the display option so that we can see all the missing values across the all series
pd.set_option('display.max_rows', 1000)
series_totals_sorted

                                                       0
series
GDP per capita (current US$)                           0
GDP (current US$)                                      0
GNI (current US$)                                      6
GDP per capita growth (annual %)                       7
GDP growth (annual %)                                  7
GNI, Atlas method (current US$)                       14
GNI per capita, Atlas method (current US$)            14
Trade (% of GDP)                                      18
Imports of goods and services (% of GDP)              18
Exports of goods and services (% of GDP)              18
Exports of goods and services (current US$)           37
Imports of goods and services (current US$)           37
Gross capital formation (current US$)                 43
Industry (including construction), value added ...    59
Manufacturing, value added (current US$)              83
Manufacturing, value added (% of GDP)                 85
Imports of goods and services (annual % growth)       94
GNI per capita growth (annual %)                     103
GNI growth (annual %)                                103
Exports of goods and services (annual % growth)      104
Manufactures imports (% of merchandise imports)      106
Agricultural raw materials imports (% of mercha...   106
External balance on goods and services (current...   112
Manufactures exports (% of merchandise exports)      113
Ores and metals exports (% of merchandise exports)   113
Agricultural raw materials exports (% of mercha...   114
Commercial service exports (current US$)             114
Commercial service imports (current US$)             116
Computer, communications and other services (% ...   117
Computer, communications and other services (% ...   132
High-technology exports (% of manufactured expo...   132
High-technology exports (current US$)                148
Export value index (2000 = 100)                      163
Import value index (2000 = 100)                      163
Manufacturing, value added (annual % growth)         164
Changes in inventories (current US$)                 194
Tariff rate, applied, simple mean, all products...   220
Tariff rate, most favored nation, weighted mean...   220
Gross value added at basic prices (GVA) (curren...   248
Start-up procedures to register a business (num...   531
Cost of business start-up procedures (% of GNI ...   531
Time required to start a business (days)             531
Research and development expenditure (% of GDP)      534
Procedures to register property (number)             571
Time required to build a warehouse (days)            611
Profit tax (% of commercial profits)                 611
Procedures to build a warehouse (number)             611
Researchers in R&D (per million people)              683
New business density (new registrations per 1,0...   826
New businesses registered (number)                   834
Investment in energy with private participation...   877
Technicians in R&D (per million people)              877
Public private partnerships investment in energ...   940
Time to export, documentary compliance (hours)      1000
Time to import, border compliance (hours)           1000
Time to export, border compliance (hours)           1000
Cost to import, border compliance (US$)             1000
Cost to import, documentary compliance (US$)        1000
Cost to export, documentary compliance (US$)        1000
Cost to export, border compliance (US$)             1000
Time to import, documentary compliance (hours)      1000
Logistics performance index: Competence and qua...  1006
Logistics performance index: Overall (1=low to ...  1006
Logistics performance index: Frequency with whi...  1006
Logistics performance index: Efficiency of cust...  1006
Logistics performance index: Ease of arranging ...  1006
Logistics performance index: Ability to track a...  1006
Logistics performance index: Quality of trade a...  1006
Lead time to export, median case (days)             1026
Lead time to import, median case (days)             1030
Average time to clear exports through customs (...  1189
Bribery incidence (% of firms experiencing at l...  1198
Ease of doing business index (1=most business-f...  1204
Firms that spend on R&D (% of firms)                1205
Public private partnerships investment in ICT (...  1226
Presence of peace keepers (number of troops, po...  1241

In [152]:
#Reset Display option
pd.reset_option('display.max_rows')

Now that we have removed some of the series that were missing a critical amount of data, we will be even more selective.

## 2014 Isolation

MCMC and Linear Interpolation

In [170]:
#Least missing values is year 2014
dfsa14 = dfsa[dfsa['year'] == '2014']
dfsa14 = dfsa14.drop(columns = ['year'])
dfsa14.set_index('country', inplace = True)
dfsa14.head()

series,Agricultural raw materials exports (% of merchandise exports),Agricultural raw materials imports (% of merchandise imports),Changes in inventories (current US$),Commercial service exports (current US$),Commercial service imports (current US$),"Computer, communications and other services (% of commercial service exports)","Computer, communications and other services (% of commercial service imports)",Cost of business start-up procedures (% of GNI per capita),"Cost to export, border compliance (US$)","Cost to export, documentary compliance (US$)",...,"Tariff rate, applied, simple mean, all products (%)","Tariff rate, most favored nation, weighted mean, all products (%)",Technicians in R&D (per million people),Time required to build a warehouse (days),Time required to start a business (days),"Time to export, border compliance (hours)","Time to export, documentary compliance (hours)","Time to import, border compliance (hours)","Time to import, documentary compliance (hours)",Trade (% of GDP)
country,,,,,,,,,,,,,,,,,,,,,
Argentina,1.07,0.89,"6,752,296,832.26","13,189,837,804.76","17,628,881,981.13",43.11,37.89,17.70,150.00,60.00,...,12.58,11.50,318.81,342.50,24.50,21.00,30.00,60.00,336.00,28.41
Australia,2.58,0.68,"-2,035,251,996.70","55,610,991,575.62","66,749,264,533.55",22.60,28.32,0.70,749.00,264.00,...,2.84,2.69,nan,112.00,2.50,36.00,7.00,37.00,3.00,42.51
Bahrain,0.03,1.04,"414,893,617.02","8,571,276,595.74","6,764,414,893.62",25.26,15.41,0.80,47.00,100.00,...,3.75,3.99,17.21,174.00,9.30,79.00,24.00,54.00,84.00,175.56
Belgium,1.39,1.27,"1,714,139,993.32","123,026,103,755.97","117,578,947,480.15",59.37,52.46,5.20,0.00,0.00,...,2.58,2.81,nan,212.00,4.00,0.00,1.00,0.00,1.00,164.70
Brazil,4.01,0.99,"16,587,335,316.62","39,046,701,888.60","85,915,546,867.55",62.78,50.47,5.50,862.00,226.40,...,13.74,9.92,nan,434.00,83.60,61.00,30.00,51.10,146.10,24.69

In [171]:
#From the following information, we can see that many series still have several NaN values across the countries
# And this is only in year 2014
dfsa14.info()

<class 'pandas.core.frame.DataFrame'>
Index: 46 entries, Argentina to Zimbabwe
Data columns (total 70 columns):
Agricultural raw materials exports (% of merchandise exports)                                                                      45 non-null float64
Agricultural raw materials imports (% of merchandise imports)                                                                      45 non-null float64
Changes in inventories (current US$)                                                                                               43 non-null float64
Commercial service exports (current US$)                                                                                           45 non-null float64
Commercial service imports (current US$)                                                                                           45 non-null float64
Computer, communications and other services (% of commercial service exports)                                                      45 non-null float64
Computer, communications and other services (% of commercial service imports)                                                      45 non-null float64
Cost of business start-up procedures (% of GNI per capita)                                                                         46 non-null float64
Cost to export, border compliance (US$)                                                                                            46 non-null float64
Cost to export, documentary compliance (US$)                                                                                       46 non-null float64
Cost to import, border compliance (US$)                                                                                            46 non-null float64
Cost to import, documentary compliance (US$)                                                                                       46 non-null float64
Export value index (2000 = 100)                                                                                                    46 non-null float64
Exports of goods and services (% of GDP)                                                                                           46 non-null float64
Exports of goods and services (annual % growth)                                                                                    45 non-null float64
Exports of goods and services (current US$)                                                                                        46 non-null float64
External balance on goods and services (current US$)                                                                               46 non-null float64
GDP (current US$)                                                                                                                  46 non-null float64
GDP growth (annual %)                                                                                                              46 non-null float64
GDP per capita (current US$)                                                                                                       46 non-null float64
GDP per capita growth (annual %)                                                                                                   46 non-null float64
GNI (current US$)                                                                                                                  46 non-null float64
GNI growth (annual %)                                                                                                              46 non-null float64
GNI per capita growth (annual %)                                                                                                   46 non-null float64
GNI per capita, Atlas method (current US$)                                                                                         46 non-null float64
GNI, Atlas method (current US$)                                                                                                    46 non-null float64
Gross capital formation (current US$)                                                                                              46 non-null float64
Gross value added at basic prices (GVA) (current US$)                                                                              38 non-null float64
High-technology exports (% of manufactured exports)                                                                                45 non-null float64
High-technology exports (current US$)                                                                                              45 non-null float64
Import value index (2000 = 100)                                                                                                    46 non-null float64
Imports of goods and services (% of GDP)                                                                                           46 non-null float64
Imports of goods and services (annual % growth)                                                                                    45 non-null float64
Imports of goods and services (current US$)                                                                                        46 non-null float64
Industry (including construction), value added (current US$)                                                                       46 non-null float64
Investment in energy with private participation (current US$)                                                                      15 non-null float64
Lead time to export, median case (days)                                                                                            40 non-null float64
Lead time to import, median case (days)                                                                                            39 non-null float64
Logistics performance index: Ability to track and trace consignments (1=low to 5=high)                                             45 non-null float64
Logistics performance index: Competence and quality of logistics services (1=low to 5=high)                                        45 non-null float64
Logistics performance index: Ease of arranging competitively priced shipments (1=low to 5=high)                                    45 non-null float64
Logistics performance index: Efficiency of customs clearance process (1=low to 5=high)                                             45 non-null float64
Logistics performance index: Frequency with which shipments reach consignee within scheduled or expected time (1=low to 5=high)    45 non-null float64
Logistics performance index: Overall (1=low to 5=high)                                                                             45 non-null float64
Logistics performance index: Quality of trade and transport-related infrastructure (1=low to 5=high)                               45 non-null float64
Manufactures exports (% of merchandise exports)                                                                                    45 non-null float64
Manufactures imports (% of merchandise imports)                                                                                    45 non-null float64
Manufacturing, value added (% of GDP)                                                                                              46 non-null float64
Manufacturing, value added (annual % growth)                                                                                       45 non-null float64
Manufacturing, value added (current US$)                                                                                           46 non-null float64
New business density (new registrations per 1,000 people ages 15-64)                                                               38 non-null float64
New businesses registered (number)                                                                                                 38 non-null float64
Ores and metals exports (% of merchandise exports)                                                                                 45 non-null float64
Procedures to build a warehouse (number)                                                                                           46 non-null float64
Procedures to register property (number)                                                                                           46 non-null float64
Profit tax (% of commercial profits)                                                                                               46 non-null float64
Public private partnerships investment in energy (current US$)                                                                     14 non-null float64
Research and development expenditure (% of GDP)                                                                                    33 non-null float64
Researchers in R&D (per million people)                                                                                            28 non-null float64
Start-up procedures to register a business (number)                                                                                46 non-null float64
Tariff rate, applied, simple mean, all products (%)                                                                                39 non-null float64
Tariff rate, most favored nation, weighted mean, all products (%)                                                                  39 non-null float64
Technicians in R&D (per million people)                                                                                            19 non-null float64
Time required to build a warehouse (days)                                                                                          46 non-null float64
Time required to start a business (days)                                                                                           46 non-null float64
Time to export, border compliance (hours)                                                                                          46 non-null float64
Time to export, documentary compliance (hours)                                                                                     46 non-null float64
Time to import, border compliance (hours)                                                                                          46 non-null float64
Time to import, documentary compliance (hours)                                                                                     46 non-null float64
Trade (% of GDP)                                                                                                                   46 non-null float64
dtypes: float64(70)
memory usage: 25.5+ KB

> locate columns that are missing a certain percentage of the data and consider how/if these should be imputed

In [172]:
# Percentage of missing data
dfsa14 = dfsa14.reset_index()
dfsa14_missing = dfsa14.isnull().sum() * 100 / len(dfsa14)
dfsa14_missing.head(50)

series
country                                                                                                                            0.00
Agricultural raw materials exports (% of merchandise exports)                                                                      2.17
Agricultural raw materials imports (% of merchandise imports)                                                                      2.17
Changes in inventories (current US$)                                                                                               6.52
Commercial service exports (current US$)                                                                                           2.17
Commercial service imports (current US$)                                                                                           2.17
Computer, communications and other services (% of commercial service exports)                                                      2.17
Computer, communications and other services (% of commercial service imports)                                                      2.17
Cost of business start-up procedures (% of GNI per capita)                                                                         0.00
Cost to export, border compliance (US$)                                                                                            0.00
Cost to export, documentary compliance (US$)                                                                                       0.00
Cost to import, border compliance (US$)                                                                                            0.00
Cost to import, documentary compliance (US$)                                                                                       0.00
Export value index (2000 = 100)                                                                                                    0.00
Exports of goods and services (% of GDP)                                                                                           0.00
Exports of goods and services (annual % growth)                                                                                    2.17
Exports of goods and services (current US$)                                                                                        0.00
External balance on goods and services (current US$)                                                                               0.00
GDP (current US$)                                                                                                                  0.00
GDP growth (annual %)                                                                                                              0.00
GDP per capita (current US$)                                                                                                       0.00
GDP per capita growth (annual %)                                                                                                   0.00
GNI (current US$)                                                                                                                  0.00
GNI growth (annual %)                                                                                                              0.00
GNI per capita growth (annual %)                                                                                                   0.00
GNI per capita, Atlas method (current US$)                                                                                         0.00
GNI, Atlas method (current US$)                                                                                                    0.00
Gross capital formation (current US$)                                                                                              0.00
Gross value added at basic prices (GVA) (current US$)                                                                             17.39
High-technology exports (% of manufactured exports)                                                                                2.17
High-technology exports (current US$)                                                                                              2.17
Import value index (2000 = 100)                                                                                                    0.00
Imports of goods and services (% of GDP)                                                                                           0.00
Imports of goods and services (annual % growth)                                                                                    2.17
Imports of goods and services (current US$)                                                                                        0.00
Industry (including construction), value added (current US$)                                                                       0.00
Investment in energy with private participation (current US$)                                                                     67.39
Lead time to export, median case (days)                                                                                           13.04
Lead time to import, median case (days)                                                                                           15.22
Logistics performance index: Ability to track and trace consignments (1=low to 5=high)                                             2.17
Logistics performance index: Competence and quality of logistics services (1=low to 5=high)                                        2.17
Logistics performance index: Ease of arranging competitively priced shipments (1=low to 5=high)                                    2.17
Logistics performance index: Efficiency of customs clearance process (1=low to 5=high)                                             2.17
Logistics performance index: Frequency with which shipments reach consignee within scheduled or expected time (1=low to 5=high)    2.17
Logistics performance index: Overall (1=low to 5=high)                                                                             2.17
Logistics performance index: Quality of trade and transport-related infrastructure (1=low to 5=high)                               2.17
Manufactures exports (% of merchandise exports)                                                                                    2.17
Manufactures imports (% of merchandise imports)                                                                                    2.17
Manufacturing, value added (% of GDP)                                                                                              0.00
Manufacturing, value added (annual % growth)                                                                                       2.17
dtype: float64

#locate columns where the number of nan values are greater than or equal to 25% of that column for all 'series'
dfsa14.loc[dfsa14['series'] == nan >= 25% ]

if count(nan) in 'series' is > (.25 * (count(x)))
    return loc[x]

In [159]:
dfsa14.head()

series,country,Agricultural raw materials exports (% of merchandise exports),Agricultural raw materials imports (% of merchandise imports),Changes in inventories (current US$),Commercial service exports (current US$),Commercial service imports (current US$),"Computer, communications and other services (% of commercial service exports)","Computer, communications and other services (% of commercial service imports)",Cost of business start-up procedures (% of GNI per capita),"Cost to export, border compliance (US$)",...,"Tariff rate, applied, simple mean, all products (%)","Tariff rate, most favored nation, weighted mean, all products (%)",Technicians in R&D (per million people),Time required to build a warehouse (days),Time required to start a business (days),"Time to export, border compliance (hours)","Time to export, documentary compliance (hours)","Time to import, border compliance (hours)","Time to import, documentary compliance (hours)",Trade (% of GDP)
0,Argentina,1.07,0.89,"6,752,296,832.26","13,189,837,804.76","17,628,881,981.13",43.11,37.89,17.70,150.00,...,12.58,11.50,318.81,342.50,24.50,21.00,30.00,60.00,336.00,28.41
1,Australia,2.58,0.68,"-2,035,251,996.70","55,610,991,575.62","66,749,264,533.55",22.60,28.32,0.70,749.00,...,2.84,2.69,nan,112.00,2.50,36.00,7.00,37.00,3.00,42.51
2,Bahrain,0.03,1.04,"414,893,617.02","8,571,276,595.74","6,764,414,893.62",25.26,15.41,0.80,47.00,...,3.75,3.99,17.21,174.00,9.30,79.00,24.00,54.00,84.00,175.56
3,Belgium,1.39,1.27,"1,714,139,993.32","123,026,103,755.97","117,578,947,480.15",59.37,52.46,5.20,0.00,...,2.58,2.81,nan,212.00,4.00,0.00,1.00,0.00,1.00,164.70
4,Brazil,4.01,0.99,"16,587,335,316.62","39,046,701,888.60","85,915,546,867.55",62.78,50.47,5.50,862.00,...,13.74,9.92,nan,434.00,83.60,61.00,30.00,51.10,146.10,24.69

In [160]:
dfsa14.isnull().sum(axis=1)

0      2
1      5
2      5
3      3
4      1
5      4
6      4
7      7
8      1
9     14
10     1
11     6
12     6
13     2
14     2
15     2
16     7
17     2
18     5
19     4
20     7
21     3
22     3
23     3
24     2
25     2
26     3
27     2
28    10
29     3
30     4
31     3
32     5
33     6
34     2
35     8
36     7
37     0
38     6
39     2
40     2
41     5
42     9
43     2
44     5
45     9
dtype: int64

My initial thought process was the following:
> `dfsa14.dropna(axis= 1, thresh= (.75 * dfsa14.apply(lambda x: x.count(), axis=0), inplace = True)`

But the Lambda call in this case takes too long/isnt computationally efficient (or necessary)

In [173]:
dfsa14.head()

series,country,Agricultural raw materials exports (% of merchandise exports),Agricultural raw materials imports (% of merchandise imports),Changes in inventories (current US$),Commercial service exports (current US$),Commercial service imports (current US$),"Computer, communications and other services (% of commercial service exports)","Computer, communications and other services (% of commercial service imports)",Cost of business start-up procedures (% of GNI per capita),"Cost to export, border compliance (US$)",...,"Tariff rate, applied, simple mean, all products (%)","Tariff rate, most favored nation, weighted mean, all products (%)",Technicians in R&D (per million people),Time required to build a warehouse (days),Time required to start a business (days),"Time to export, border compliance (hours)","Time to export, documentary compliance (hours)","Time to import, border compliance (hours)","Time to import, documentary compliance (hours)",Trade (% of GDP)
0,Argentina,1.07,0.89,"6,752,296,832.26","13,189,837,804.76","17,628,881,981.13",43.11,37.89,17.70,150.00,...,12.58,11.50,318.81,342.50,24.50,21.00,30.00,60.00,336.00,28.41
1,Australia,2.58,0.68,"-2,035,251,996.70","55,610,991,575.62","66,749,264,533.55",22.60,28.32,0.70,749.00,...,2.84,2.69,nan,112.00,2.50,36.00,7.00,37.00,3.00,42.51
2,Bahrain,0.03,1.04,"414,893,617.02","8,571,276,595.74","6,764,414,893.62",25.26,15.41,0.80,47.00,...,3.75,3.99,17.21,174.00,9.30,79.00,24.00,54.00,84.00,175.56
3,Belgium,1.39,1.27,"1,714,139,993.32","123,026,103,755.97","117,578,947,480.15",59.37,52.46,5.20,0.00,...,2.58,2.81,nan,212.00,4.00,0.00,1.00,0.00,1.00,164.70
4,Brazil,4.01,0.99,"16,587,335,316.62","39,046,701,888.60","85,915,546,867.55",62.78,50.47,5.50,862.00,...,13.74,9.92,nan,434.00,83.60,61.00,30.00,51.10,146.10,24.69